package com.example.securityutilitysuite.service;

import com.example.securityutilitysuite.enums.Severity;
import com.example.securityutilitysuite.enums.ThreatType;
import com.example.securityutilitysuite.model.SecurityLogAlert;
import com.example.securityutilitysuite.repository.SecurityLogAlertRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Parses web server access logs (Apache/Nginx "combined log" style) and
 * flags suspicious activity: brute-force login attempts, error-status
 * spikes (404/500, often reconnaissance or broken deployments),
 * repeated unauthorized-access attempts (403), and lines carrying
 * classic SQL-injection or XSS payload signatures.
 *
 * Design notes:
 * - Stateless per call: every analysis run receives raw log text, does
 *   all detection in memory, and persists only the resulting alerts —
 *   no partial state is kept between requests.
 * - Rule-based, not ML-based: thresholds are simple counters. This is
 *   intentional for a first version — transparent, explainable findings
 *   are more useful for a learning/demo tool than an opaque model.
 * - Per-IP aggregation for count-based rules (brute-force, error spikes,
 *   403s), but per-line signature matching for injection-style attacks,
 *   since a single malicious request is meaningful on its own.
 */
@Service
public class LogAnalyzerService {

    private static final int BRUTE_FORCE_THRESHOLD = 3;   // failed logins (401) from one IP
    private static final int ERROR_SPIKE_THRESHOLD = 3;   // 404/500 responses from one IP
    private static final int FORBIDDEN_THRESHOLD = 2;     // 403 responses from one IP

    // Apache/Nginx combined log format:
    // IP - - [timestamp] "METHOD PATH PROTOCOL" STATUS SIZE ...
    private static final Pattern LOG_LINE_PATTERN = Pattern.compile(
            "^(\\S+)\\s+\\S+\\s+\\S+\\s+\\[([^]]+)]\\s+\"(\\S+)\\s+(\\S+)[^\"]*\"\\s+(\\d{3})\\s+(\\S+)"
    );

    private static final Pattern SQLI_PATTERN = Pattern.compile(
            "(?i)(\\bunion\\s+select\\b|\\bor\\s+1\\s*=\\s*1\\b|'\\s*or\\s*'1'\\s*=\\s*'1|--\\s|;\\s*drop\\s+table|\\bselect\\b.{0,40}\\bfrom\\b.{0,40}\\bwhere\\b)"
    );

    private static final Pattern XSS_PATTERN = Pattern.compile(
            "(?i)(<script|onerror\\s*=|onload\\s*=|javascript:|<img[^>]+onerror)"
    );

    private final SecurityLogAlertRepository repository;

    public LogAnalyzerService(SecurityLogAlertRepository repository) {
        this.repository = repository;
    }

    /**
     * Parses the given log text, runs all detection rules, persists any
     * resulting alerts, and returns just the alerts generated by this run
     * (not the full history).
     */
    @Transactional
    public List<SecurityLogAlert> analyze(String logContent, String logSource) {
        String source = (logSource == null || logSource.isBlank()) ? "manual-paste" : logSource;

        List<ParsedLine> parsedLines = parseLines(logContent);
        List<SecurityLogAlert> alerts = new ArrayList<>();

        alerts.addAll(detectPerIpPatterns(parsedLines, source));
        alerts.addAll(detectInjectionSignatures(parsedLines, source));

        return repository.saveAll(alerts);
    }

    @Transactional(readOnly = true)
    public Page<SecurityLogAlert> getAlerts(Pageable pageable) {
        return repository.findAll(pageable);
    }

    // ------------------------------------------------------------------
    // Parsing
    // ------------------------------------------------------------------

    private record ParsedLine(String raw, String ip, String path, int status) {
    }

    private List<ParsedLine> parseLines(String logContent) {
        List<ParsedLine> result = new ArrayList<>();
        for (String line : logContent.split("\\R")) {
            if (line.isBlank()) continue;

            Matcher m = LOG_LINE_PATTERN.matcher(line.trim());
            if (m.find()) {
                String ip = m.group(1);
                String path = m.group(4);
                int status;
                try {
                    status = Integer.parseInt(m.group(5));
                } catch (NumberFormatException ex) {
                    status = -1;
                }
                result.add(new ParsedLine(line.trim(), ip, path, status));
            } else {
                // Doesn't match the combined log format — still keep it so
                // injection-signature scanning can check its raw text.
                result.add(new ParsedLine(line.trim(), "unknown", "", -1));
            }
        }
        return result;
    }

    // ------------------------------------------------------------------
    // Per-IP count-based detection (brute-force, error spikes, 403s)
    // ------------------------------------------------------------------

    private List<SecurityLogAlert> detectPerIpPatterns(List<ParsedLine> lines, String source) {
        Map<String, List<ParsedLine>> byIp = new LinkedHashMap<>();
        for (ParsedLine line : lines) {
            if (!"unknown".equals(line.ip())) {
                byIp.computeIfAbsent(line.ip(), k -> new ArrayList<>()).add(line);
            }
        }

        List<SecurityLogAlert> alerts = new ArrayList<>();

        for (Map.Entry<String, List<ParsedLine>> entry : byIp.entrySet()) {
            String ip = entry.getKey();
            List<ParsedLine> ipLines = entry.getValue();

            long failedLogins = ipLines.stream().filter(l -> l.status() == 401).count();
            long errorSpikes = ipLines.stream().filter(l -> l.status() == 404 || l.status() == 500).count();
            long forbidden = ipLines.stream().filter(l -> l.status() == 403).count();

            if (failedLogins >= BRUTE_FORCE_THRESHOLD) {
                alerts.add(buildAlert(
                        ip, source, ThreatType.BRUTE_FORCE,
                        failedLogins >= 8 ? Severity.CRITICAL : Severity.HIGH,
                        String.format("IP %s: %d saniyeler içinde %d başarısız giriş denemesi (401)", ip, ipLines.size(), failedLogins),
                        sampleRawLogs(ipLines, l -> l.status() == 401)
                ));
            }

            if (errorSpikes >= ERROR_SPIKE_THRESHOLD) {
                alerts.add(buildAlert(
                        ip, source, ThreatType.SUSPICIOUS_ACTIVITY,
                        Severity.MEDIUM,
                        String.format("IP %s: %d adet 404/500 yanıtı — olası dizin/endpoint tarama denemesi", ip, errorSpikes),
                        sampleRawLogs(ipLines, l -> l.status() == 404 || l.status() == 500)
                ));
            }

            if (forbidden >= FORBIDDEN_THRESHOLD) {
                alerts.add(buildAlert(
                        ip, source, ThreatType.SUSPICIOUS_ACTIVITY,
                        Severity.HIGH,
                        String.format("IP %s: %d adet 403 yanıtı — yetkisiz erişim denemesi", ip, forbidden),
                        sampleRawLogs(ipLines, l -> l.status() == 403)
                ));
            }
        }

        return alerts;
    }

    // ------------------------------------------------------------------
    // Per-line signature detection (SQLi / XSS)
    // ------------------------------------------------------------------

    private List<SecurityLogAlert> detectInjectionSignatures(List<ParsedLine> lines, String source) {
        List<SecurityLogAlert> alerts = new ArrayList<>();

        for (ParsedLine line : lines) {
            // Parse edilemeyen satirlarda path "" (bos string) olarak gelir — null degil.
            // Bu yuzden null kontrolu yeterli degil; isBlank() ile ham satira dusuyoruz.
            String candidate = (line.path() == null || line.path().isBlank())
                    ? line.raw()
                    : line.path();

            // Gercek loglarda saldiri payload'lari URL-encoded gelir: bosluklar
            // %20 veya + olur. Imza regex'leri ise \s (bosluk) bekliyor. Decode
            // etmeden "union%20select" gibi klasik saldirilar hic yakalanmiyordu.
            String haystack = safeUrlDecode(candidate);

            if (SQLI_PATTERN.matcher(haystack).find()) {
                alerts.add(buildAlert(
                        line.ip(), source, ThreatType.SQL_INJECTION, Severity.CRITICAL,
                        "SQL enjeksiyonu imzasına uyan istek tespit edildi",
                        line.raw()
                ));
            }

            if (XSS_PATTERN.matcher(haystack).find()) {
                alerts.add(buildAlert(
                        line.ip(), source, ThreatType.XSS, Severity.HIGH,
                        "XSS (cross-site scripting) imzasına uyan istek tespit edildi",
                        line.raw()
                ));
            }
        }

        return alerts;
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private SecurityLogAlert buildAlert(String ip, String source, ThreatType type, Severity severity,
                                         String summary, String rawLog) {
        return SecurityLogAlert.builder()
                .ipAddress(ip)
                .logSource(source)
                .threatType(type)
                .severity(severity)
                .rawLog(summary + "\n" + rawLog)
                .build();
    }

    /**
     * URL-decode eder; bozuk yuzde dizileri (orn. tek basina "%" veya "%zz")
     * loglarda sik gorulur ve {@link URLDecoder} bunlarda
     * {@link IllegalArgumentException} firlatir. Boyle bir durumda metni
     * oldugu gibi dondururuz — tespit yapmamak, patlamaktan iyidir.
     */
    private String safeUrlDecode(String value) {
        if (value == null || value.isEmpty()) {
            return "";
        }
        try {
            return URLDecoder.decode(value, StandardCharsets.UTF_8);
        } catch (IllegalArgumentException ex) {
            return value;
        }
    }

    private String sampleRawLogs(List<ParsedLine> lines, java.util.function.Predicate<ParsedLine> filter) {
        return lines.stream()
                .filter(filter)
                .limit(3)
                .map(ParsedLine::raw)
                .reduce((a, b) -> a + "\n" + b)
                .orElse("");
    }
}
