# Spring Application Name
spring.application.name=security-utility-suite

# Varsayılan Profil (H2)
spring.profiles.active=dev

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:SecuritySuiteDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Properties (H2)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# H2 Console (Tarayıcıdan veritabanını görmek için: http://localhost:8080/h2-console)
spring.h2.console.enabled=true